{% set name = "gptcache" %}
{% set version = "0.1.24" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gptcache-{{ version }}.tar.gz
  sha256: aa591cb00898d457a50a5e0cd137d0119e86819c110ce6c7bce2adafeae0a467

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - openai
    - numpy
    - cachetools

test:
  imports:
    - gptcache
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/zilliztech/GPTCache
  summary: GPTCache, a powerful caching library that can be used to speed up and lower the cost of chat applications that rely on the LLM service. GPTCache works as a memcache for AIGC applications, similar to how Redis works for traditional applications.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - YYYasin19
